version: "3.9"

services:
  php:
    container_name: todolist-php
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    container_name: todolist-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    restart: always

  postgres:
    container_name: todolist-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always

  testdb:
    container_name: todolist-testdb
    image: postgres:latest
    environment:
      POSTGRES_DB: ${TEST_DB_DATABASE}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "5433:5432"
    restart: always

  elasticsearch:
    container_name: todolist-es
    image: elasticsearch:${ES_VERSION}
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
      ES_USER: ${ES_USER}
      ES_PASSWORD: ${ES_PASSWORD}
      ES_MEMORY: 2g
    ports:
      - "9200:9200"

networks:
  default:
    name: my_network
